---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: mongodb
      version: 7.6.3
      sourceRef:
        kind: mongodb
        name: podinfo
        namespace: flux-system
      interval: 1m  
  values:
    image:
      repository: bitnami/mongodb
      tag: 4.0.20
    usePassword: false
    persistence:
      enabled: false
    securityContext:
      enabled: true
      fsGroup: 0
      runAsUser: 0
